### ISSUE TITLE
No module named 'wget'

### ISSUE THREAD

**Issue by Rubenacp** [jhj0517/stable-diffusion-webui-MusePose#1]
Thanks for implemented this tool for WebUI. I tried to install with your instructions but when I start WebUI can't install it.

*** Error loading script: musepose.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-MusePose\scripts\musepose.py", line 8, in <module>
        from scripts.musepose_modules.pose_align import PoseAlignmentInference
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-MusePose\scripts\musepose_modules\pose_align.py", line 12, in <module>
        from scripts.musepose_modules.downloading_weights import download_models
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-MusePose\scripts\musepose_modules\downloading_weights.py", line 2, in <module>
        import wget
    ModuleNotFoundError: No module named 'wget'

**Comment by jhj0517** [comment]
Hi, I've just added wget in #2, 
Can you try latest version?

**Comment by Rubenacp** [comment]
Thank you. The installation of the extension and the download of the models was correct, but now I get this error:

9it [00:00, 8994.22it/s]
3it [00:00, ?it/s]
height: 762.0
width: 638.0
fps: 30.0
06/06 17:55:26 - mmengine - WARNING - The current default scope "mmpose" is not "mmdet", `init_default_scope` will force set the currentdefault scope to "mmdet".
Loads checkpoint by local backend from path: G:\stable-diffusion-webui\models\dwpose\yolox_l_8x8_300e_coco.pth
06/06 17:55:27 - mmengine - WARNING - The current default scope "mmdet" is not "mmpose", `init_default_scope` will force set the currentdefault scope to "mmpose".
Loads checkpoint by local backend from path: G:\stable-diffusion-webui\models\dwpose\dw-ll_ucoco_384.pth
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-MusePose\scripts\musepose_modules\pose_align.py", line 99, in align_pose
    cv2.destroyAllWindows()             # 关闭所有窗口
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by Rubenacp** [comment]
Do I need to adjust "Detect Resolution or Image Resolution" in based on the image and video I upload?

**Comment by jhj0517** [comment]
In SD WebUI it worked fine, but I got the same error just now in the Forge. Are you using Forge?

According to [opencv-python #18]( https://github.com/opencv/opencv-python/issues/18#issuecomment-752701731), The problem is `opencv-python-headless`. 

As I tested, SD WebUI does not have `opencv-python-headless` by default so it works fine. 
But in Forge, it has `opencv-python-headless` by default and it's problematic.





>> Do I need to adjust "Detect Resolution or Image Resolution" in based on the image and video I upload?

No. It will automatically resize the input images and videos.

**Comment by jhj0517** [comment]
>> Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

To resolve this issue, You have to
```
# Activating venv  
pip uninstall opencv-python-headless
pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip install opencv-python
pip install opencv-contrib-python
```

I'll add about this in the ReadMe.

**Comment by Rubenacp** [comment]
I don't use Forge, I installed it in the normal automatic 1111 in windows 11. I will try it. 
 One more question because I have a basic knowledge, how can I "Activating venv " 
many thanks

**Comment by jhj0517** [comment]
@Rubenacp 

Open the terminal in the WebUI project folder and run `venv\Scripts\activate` like this.
```
C:\YourPath\To_SD_WebUI>venv\Scripts\activate
```

Then it will display `(venv)` in front of the terminal like this
```
(venv) C:\YourPath\To_SD_WebUI>
```

In this state, you can run 
```
pip uninstall opencv-python-headless
pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip install opencv-python
pip install opencv-contrib-python
```

**Comment by Rubenacp** [comment]
It absolutely does work when following the steps you gave me.

It's a little slow because I only have 12 VRAM, but I'll try smaller resolutions than 512

thank you so much,
